# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
$username\
[@](green bold)\
$hostname\
[ on ](blue)\
$os\
$shell\
$all\
"""

### ALTERNATE prompt format ###
# format = """
# [╭─user───❯](bold blue) $username
# [┣─system─❯](bold yellow) $hostname
# [┣─project❯](bold red) $directory$rust$git_branch$git_state$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
# [╰─cmd────❯](bold green)
# """

### OLD prompt format ### 
# format = """\
# [╭╴](blue)\
# $all\
# $fill\
# $os\
# $shell\
# $line_break\
# [╰─](blue)\
# $character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

[fill]
symbol = " "

[os]
disabled = false

[os.symbols]
Arch = "[](green) "
Debian = " "
Fedora = " "
Ubuntu = " "
Windows = " "

[shell]
disabled = false
powershell_indicator = "pwsh"
bash_indicator = "[bash](green)"

# Shows the username
[username]
style_user = "yellow bold"
style_root = "root bold"
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold yellow)'
disabled = false

[directory]
truncation_length = 4
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[in](blue) [$path]($style)[$read_only]($read_only_style) "

#  - alternate git branch logo
[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = ".../"
style = "bold green"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰓜 "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = " "

[docker_context]
format = "via [ $context](bold blue) "

[python]
symbol = " "

[rust]
symbol = " "

[java]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[nodejs]
format = "via [ $version](bold green) "

[ruby]
format = "via [ $version]($style) "

[kubernetes]
format = 'on [󱃾 $context\($namespace\)](bold purple) '
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"
